version: "3"
services:
    raamatud-api:
        image: hs9-flask-api-raamatud
        ports:
            - 5000:5000
        env_file: .env

    raamatud-otsing-api:
        image: hs9-flask-api-raamatute-otsing
        ports:
            - 5001:5000
        env_file: .env